development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: qwerty
  pool: 5
  username: postgres
  password: credicope123!

test:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: qwerty-dev
  pool: 5
  username: postgres
  password: credicope123!